# Generated by Django 6.0.3 on 2026-04-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_sample_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='education',
            name='year_end',
            field=models.IntegerField(blank=True, help_text='Leave blank if currently attending', null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('language', 'Programming Language'), ('framework', 'Framework / Library'), ('editing', 'Editing Softwares'), ('tool', 'Tool / Software'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
