# Generated by Django 6.0.3 on 2026-04-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_profile_options_alter_education_year_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tiktok_link',
            field=models.URLField(blank=True),
        ),
    ]
